-- =============================================================================
-- 元数据治理平台 · 核心库 DDL
-- 目标：PostgreSQL 14+
-- 配套文档：01-data-model-design.md
-- 说明：本文件为初始建表脚本；后续变更一律通过 Alembic 管理，勿手工改库
-- =============================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pg_trgm;      -- 表名/字段名模糊检索
CREATE EXTENSION IF NOT EXISTS btree_gin;    -- 标量 + JSONB 组合索引

-- 如需独立 schema，取消下一行注释并统一替换表名前缀
-- CREATE SCHEMA IF NOT EXISTS mdm;
-- SET search_path TO mdm, public;

-- =============================================================================
-- 1. 租户（预留，单租户时全填 0）
-- =============================================================================
CREATE TABLE tenant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          TEXT        NOT NULL,
    name          TEXT        NOT NULL,
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_tenant_code ON tenant (code);

-- =============================================================================
-- 2. 数据源与凭据
-- =============================================================================
CREATE TABLE datasource (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT      NOT NULL DEFAULT 0,
    code            TEXT        NOT NULL,
    name            TEXT        NOT NULL,
    ds_type         TEXT        NOT NULL,   -- mysql / postgres / snowflake / sqlserver / bigquery
    host            TEXT,
    port            INTEGER,

    -- 环境标识、分组与负责人（FR-1.7 ~ FR-1.9）
    environment     TEXT,                    -- prod / test / dev
    group_name      TEXT,
    owner_business  TEXT,
    owner_technical TEXT,

    -- 采集策略
    enabled         BOOLEAN     NOT NULL DEFAULT TRUE,
    scan_enabled    BOOLEAN     NOT NULL DEFAULT TRUE,
    sampling_enabled BOOLEAN    NOT NULL DEFAULT FALSE,  -- 默认关闭，见 FR-8 / Q7
    scan_config     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    --   {"include_schemas":[], "exclude_schemas":[], "include_tables":[],
    --    "exclude_tables":[], "max_concurrency":4, "cron":"0 2 * * *"}
    sampling_config JSONB       NOT NULL DEFAULT '{}'::jsonb,
    --   {"sample_rate":1.0, "max_rows":100000, "timeout_seconds":60,
    --    "large_table_threshold":100000000, "sensitive_blacklist":[]}

    -- 能力位（由连接器探测或配置，FR-8.5）
    supports_sampling  BOOLEAN  NOT NULL DEFAULT FALSE,
    supports_lineage   BOOLEAN  NOT NULL DEFAULT FALSE,
    supports_profiling BOOLEAN  NOT NULL DEFAULT FALSE,

    -- 健康度
    last_scan_at    TIMESTAMPTZ,
    last_scan_status TEXT,
    last_error      TEXT,

    deleted_at      TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_datasource_type CHECK (
        ds_type IN ('mysql','postgres','snowflake','sqlserver','bigquery','other')
    )
);
CREATE UNIQUE INDEX uq_datasource_code ON datasource (code) WHERE deleted_at IS NULL;
CREATE INDEX idx_datasource_tenant ON datasource (tenant_id) WHERE deleted_at IS NULL;

COMMENT ON COLUMN datasource.scan_config      IS '采集策略：黑白名单、并发、调度';
COMMENT ON COLUMN datasource.sampling_config  IS '采样策略：采样率、上限、超时、大表熔断阈值、敏感列黑名单';
COMMENT ON COLUMN datasource.supports_sampling IS 'MySQL 无 TABLESAMPLE，需由方言层置位并走替代策略';

-- 凭据独立表：支持多版本轮换，密文由应用层加密（密钥不入库）
CREATE TABLE datasource_credential (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    datasource_id  BIGINT      NOT NULL REFERENCES datasource (id),
    version        INTEGER     NOT NULL DEFAULT 1,
    username       TEXT,
    credential_enc BYTEA       NOT NULL,     -- 应用层加密后的口令/密钥材料
    enc_algo       TEXT        NOT NULL DEFAULT 'AES-256-GCM',
    is_active      BOOLEAN     NOT NULL DEFAULT TRUE,
    verified_at    TIMESTAMPTZ,
    expires_at     TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_dscred_active
    ON datasource_credential (datasource_id) WHERE is_active;
CREATE INDEX idx_dscred_ds ON datasource_credential (datasource_id, version DESC);

-- =============================================================================
-- 3. 元数据实体（catalog_*）
-- =============================================================================
CREATE TABLE catalog_database (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    name          TEXT        NOT NULL,
    fqn           TEXT        NOT NULL,
    description   TEXT,
    owner         TEXT,
    tags          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    properties    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_catdb_fqn ON catalog_database (fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_catdb_ds ON catalog_database (datasource_id) WHERE deleted_at IS NULL;

CREATE TABLE catalog_schema (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    database_id   BIGINT      NOT NULL REFERENCES catalog_database (id),
    name          TEXT        NOT NULL,
    fqn           TEXT        NOT NULL,
    description   TEXT,
    owner         TEXT,
    tags          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    properties    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_catsch_fqn ON catalog_schema (fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_catsch_db ON catalog_schema (database_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_catsch_ds ON catalog_schema (datasource_id) WHERE deleted_at IS NULL;

CREATE TABLE catalog_table (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    schema_id     BIGINT      NOT NULL REFERENCES catalog_schema (id),
    name          TEXT        NOT NULL,
    fqn           TEXT        NOT NULL,
    table_type    TEXT,                      -- TABLE / VIEW / MATERIALIZED_VIEW / EXTERNAL
    description   TEXT,
    owner         TEXT,
    tags          JSONB       NOT NULL DEFAULT '[]'::jsonb,
    properties    JSONB       NOT NULL DEFAULT '{}'::jsonb,

    -- 冗余：详情接口一次读取，避免 N 行 join（决策 A）
    columns_json  JSONB       NOT NULL DEFAULT '[]'::jsonb,
    column_count  INTEGER     NOT NULL DEFAULT 0,

    -- 结构签名 + 分级冗余（决策 E / F）
    struct_hash   TEXT,
    grade_level   SMALLINT,
    grade_code    TEXT,

    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_table_grade CHECK (grade_level IS NULL OR grade_level BETWEEN 1 AND 9)
);
CREATE UNIQUE INDEX uq_cattab_fqn ON catalog_table (fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_cattab_keyset ON catalog_table (fqn, id) WHERE deleted_at IS NULL;
CREATE INDEX idx_cattab_ds_keyset ON catalog_table (datasource_id, fqn, id) WHERE deleted_at IS NULL;
CREATE INDEX idx_cattab_schema ON catalog_table (schema_id, name) WHERE deleted_at IS NULL;
CREATE INDEX idx_cattab_grade ON catalog_table (grade_level) WHERE deleted_at IS NULL;
CREATE INDEX idx_cattab_name_trgm ON catalog_table USING gin (name gin_trgm_ops);
CREATE INDEX idx_cattab_tags ON catalog_table USING gin (tags jsonb_path_ops);

COMMENT ON COLUMN catalog_table.columns_json IS '字段冗余缓存，以 catalog_column 为准，可由重建任务按 table_id 重刷';
COMMENT ON COLUMN catalog_table.struct_hash  IS 'md5(按 ordinal 拼接的字段签名)，用于增量判定与 Diff 前置过滤';

-- 核心大表：字段（MVP 不分区，触发条件见设计文档 §5.1）
CREATE TABLE catalog_column (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id        BIGINT      NOT NULL DEFAULT 0,
    datasource_id    BIGINT      NOT NULL REFERENCES datasource (id),
    table_id         BIGINT      NOT NULL REFERENCES catalog_table (id),
    name             TEXT        NOT NULL,
    fqn              TEXT        NOT NULL,
    ordinal_position INTEGER,
    data_type        TEXT,                   -- 归一化类型
    data_type_display TEXT,                  -- 源库原始类型串
    data_length      INTEGER,
    numeric_precision INTEGER,
    numeric_scale    INTEGER,
    nullable         BOOLEAN     NOT NULL DEFAULT TRUE,
    default_value    TEXT,
    description      TEXT,

    children         JSONB       NOT NULL DEFAULT '[]'::jsonb,  -- 嵌套类型不打散（决策 B）
    tags             JSONB       NOT NULL DEFAULT '[]'::jsonb,
    properties       JSONB       NOT NULL DEFAULT '{}'::jsonb,

    struct_hash      TEXT,
    grade_level      SMALLINT,
    grade_code       TEXT,

    deleted_at       TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_column_grade CHECK (grade_level IS NULL OR grade_level BETWEEN 1 AND 9)
);
CREATE UNIQUE INDEX uq_catcol_fqn ON catalog_column (fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_keyset ON catalog_column (fqn, id) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_ds_keyset ON catalog_column (datasource_id, fqn, id) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_table ON catalog_column (table_id, ordinal_position) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_grade ON catalog_column (grade_level) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_datatype ON catalog_column (data_type) WHERE deleted_at IS NULL;
CREATE INDEX idx_catcol_name_trgm ON catalog_column USING gin (name gin_trgm_ops);
CREATE INDEX idx_catcol_tags ON catalog_column USING gin (tags jsonb_path_ops);

-- =============================================================================
-- 4. 数据画像与质量
-- =============================================================================
CREATE TABLE table_profile (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    table_id      BIGINT      NOT NULL REFERENCES catalog_table (id),
    row_count     BIGINT,
    column_count  INTEGER,
    size_bytes    BIGINT,
    -- per-column 统计：{"col": {"null_count":..,"distinct_count":..,"min":..,
    --                   "max":..,"mean":..,"stddev":..,"top_values":[..]}}
    stats         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    sample_rate   NUMERIC(6,4),
    sampled_rows  BIGINT,
    profiled_at   TIMESTAMPTZ,
    duration_ms   INTEGER,
    status        TEXT        NOT NULL DEFAULT 'pending',
    error_message TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_profile_status CHECK (status IN ('pending','running','success','failed','skipped'))
);
CREATE UNIQUE INDEX uq_profile_table ON table_profile (table_id);
CREATE INDEX idx_profile_ds ON table_profile (datasource_id, profiled_at DESC);

CREATE TABLE quality_rule (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    code          TEXT        NOT NULL,
    name          TEXT        NOT NULL,
    rule_type     TEXT        NOT NULL,   -- not_null / unique / range_check / pattern_match / referential / custom_sql
    target_type   TEXT        NOT NULL,   -- table / column
    definition    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    severity      TEXT        NOT NULL DEFAULT 'warning',
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_qrule_code ON quality_rule (code);

CREATE TABLE quality_result (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scan_run_id   BIGINT,
    table_id      BIGINT      NOT NULL REFERENCES catalog_table (id),
    column_id     BIGINT      REFERENCES catalog_column (id),
    rule_id       BIGINT      NOT NULL REFERENCES quality_rule (id),
    passed        BOOLEAN     NOT NULL,
    metric_value  NUMERIC,
    detail        JSONB       NOT NULL DEFAULT '{}'::jsonb,
    executed_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_qresult_table ON quality_result (table_id, executed_at DESC);
CREATE INDEX idx_qresult_rule ON quality_result (rule_id, executed_at DESC);

-- =============================================================================
-- 5. 分类分级
-- =============================================================================
CREATE TABLE classification_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL DEFAULT 0,
    tag_key     TEXT        NOT NULL,        -- pii_phone / pii_idcard / ...
    tag_name    TEXT        NOT NULL,        -- 手机号
    category    TEXT,                        -- PII / 财务 / 业务
    grade_level SMALLINT,
    grade_code  TEXT,                        -- L1..L4
    color       TEXT,
    description TEXT,
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_clstag_grade CHECK (grade_level IS NULL OR grade_level BETWEEN 1 AND 9)
);
CREATE UNIQUE INDEX uq_clstag_key ON classification_tag (tag_key);
CREATE INDEX idx_clstag_grade ON classification_tag (grade_level);

CREATE TABLE classification_rule (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL DEFAULT 0,
    tag_key     TEXT        NOT NULL,
    rule_kind   TEXT        NOT NULL,   -- column_name / regex / data_type / sample_verify
    pattern     TEXT,                   -- 词典词或正则
    options     JSONB       NOT NULL DEFAULT '{}'::jsonb,
    confidence  NUMERIC(4,3) NOT NULL DEFAULT 0.800,
    priority    INTEGER     NOT NULL DEFAULT 100,
    enabled     BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_clsrule_tag ON classification_rule (tag_key, enabled);

-- 打标结果（大表，可能 2000–5000 万行）
CREATE TABLE entity_tag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT      NOT NULL DEFAULT 0,
    entity_type TEXT        NOT NULL,   -- database / schema / table / column
    entity_id   BIGINT      NOT NULL,
    entity_fqn  TEXT,
    tag_key     TEXT        NOT NULL,
    grade_level SMALLINT,
    source      TEXT        NOT NULL,   -- rule / sample / manual
    confidence  NUMERIC(4,3),
    applied_by  TEXT,
    applied_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ,
    CONSTRAINT ck_etag_type CHECK (entity_type IN ('database','schema','table','column')),
    CONSTRAINT ck_etag_source CHECK (source IN ('rule','sample','manual'))
);
CREATE UNIQUE INDEX uq_etag_entity_tag
    ON entity_tag (entity_type, entity_id, tag_key) WHERE deleted_at IS NULL;
CREATE INDEX idx_etag_entity ON entity_tag (entity_type, entity_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_etag_key ON entity_tag (tag_key) WHERE deleted_at IS NULL;
CREATE INDEX idx_etag_grade ON entity_tag (grade_level) WHERE deleted_at IS NULL;

COMMENT ON COLUMN entity_tag.source IS 'manual 来源的标签，自动引擎不得覆盖（FR-9.5）';

-- =============================================================================
-- 6. 扫描批次
-- =============================================================================
CREATE TABLE scan_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      REFERENCES datasource (id),
    job_type      TEXT        NOT NULL,   -- metadata / profile / sample / classify / lineage / permission
    trigger_type  TEXT,                   -- manual / scheduled / api
    status        TEXT        NOT NULL DEFAULT 'pending',
    -- 建议与 core/engine/state.py:270-291 的 7 状态对齐后固化
    started_at    TIMESTAMPTZ,
    finished_at   TIMESTAMPTZ,
    duration_ms   INTEGER,
    stats         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    error_message TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_scanrun_ds ON scan_run (datasource_id, created_at DESC);
CREATE INDEX idx_scanrun_type_status ON scan_run (job_type, status, created_at DESC);

-- =============================================================================
-- 7. 快照（按月分区 —— 增长最快，保留窗口外 DROP PARTITION）
-- =============================================================================
CREATE TABLE table_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date DATE        NOT NULL,
    scan_run_id   BIGINT      NOT NULL,
    datasource_id BIGINT      NOT NULL,
    table_id      BIGINT      NOT NULL,
    fqn           TEXT        NOT NULL,
    struct_hash   TEXT,
    snapshot_json JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, snapshot_date)
) PARTITION BY RANGE (snapshot_date);
CREATE INDEX idx_tsnap_run ON table_snapshot (scan_run_id);
CREATE INDEX idx_tsnap_table ON table_snapshot (table_id, snapshot_date DESC);

CREATE TABLE column_snapshot (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    snapshot_date DATE        NOT NULL,
    scan_run_id   BIGINT      NOT NULL,
    datasource_id BIGINT      NOT NULL,
    table_id      BIGINT      NOT NULL,
    column_id     BIGINT      NOT NULL,
    fqn           TEXT        NOT NULL,
    ordinal_position INTEGER,
    struct_hash   TEXT,
    snapshot_json JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, snapshot_date)
) PARTITION BY RANGE (snapshot_date);
CREATE INDEX idx_csnap_run ON column_snapshot (scan_run_id);
CREATE INDEX idx_csnap_column ON column_snapshot (column_id, snapshot_date DESC);

-- 分区需由运维/Alembic 每月预建；不建议建 DEFAULT 分区（会阻塞后续 ATTACH）
-- 示例：
-- CREATE TABLE table_snapshot_2026_10 PARTITION OF table_snapshot
--     FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
-- CREATE TABLE column_snapshot_2026_10 PARTITION OF column_snapshot
--     FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');

-- =============================================================================
-- 8. 变更事件（按月分区）
-- =============================================================================
CREATE TABLE change_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    detected_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    scan_run_id  BIGINT,
    datasource_id BIGINT,
    entity_type  TEXT        NOT NULL,   -- table / column
    entity_id    BIGINT,
    entity_fqn   TEXT,
    change_type  TEXT        NOT NULL,   -- added / deleted / modified / renamed
    severity     TEXT        NOT NULL,   -- breaking / structural / descriptive
    before_json  JSONB,
    after_json   JSONB,
    notified     BOOLEAN     NOT NULL DEFAULT FALSE,
    ack_status   TEXT        NOT NULL DEFAULT 'pending',  -- pending / closed (T-204)
    ack_action   TEXT,                                    -- acknowledged / rejected / ignored
    ack_by       TEXT,
    ack_at       TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, detected_at),
    CONSTRAINT ck_change_type CHECK (change_type IN ('table_added','table_removed','table_renamed','column_added','column_removed','column_renamed','type_changed','nullable_changed','comment_changed')),
    CONSTRAINT ck_change_sev  CHECK (severity IN ('breaking','structural','descriptive')),
    CONSTRAINT ck_change_ack  CHECK (ack_status IN ('pending','closed'))
) PARTITION BY RANGE (detected_at);
CREATE INDEX idx_change_run ON change_event (scan_run_id);
CREATE INDEX idx_change_sev ON change_event (severity, detected_at DESC);
CREATE INDEX idx_change_entity ON change_event (entity_type, entity_fqn, detected_at DESC);
CREATE INDEX idx_change_ack ON change_event (ack_status, detected_at DESC);

-- =============================================================================
-- 9. 血缘
-- =============================================================================
CREATE TABLE lineage_table_edge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL DEFAULT 0,
    src_fqn      TEXT        NOT NULL,
    tgt_fqn      TEXT        NOT NULL,
    src_table_id BIGINT,
    tgt_table_id BIGINT,
    edge_source  TEXT        NOT NULL,   -- view / sql_parse / manual / etl_system
    confidence   NUMERIC(4,3) NOT NULL DEFAULT 1.000,
    properties   JSONB       NOT NULL DEFAULT '{}'::jsonb,
    deleted_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_lte_edge ON lineage_table_edge (src_fqn, tgt_fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_lte_src ON lineage_table_edge (src_fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_lte_tgt ON lineage_table_edge (tgt_fqn) WHERE deleted_at IS NULL;

CREATE TABLE lineage_column_edge (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT      NOT NULL DEFAULT 0,
    src_fqn      TEXT        NOT NULL,
    tgt_fqn      TEXT        NOT NULL,
    src_column_id BIGINT,
    tgt_column_id BIGINT,
    edge_source  TEXT        NOT NULL,
    confidence   NUMERIC(4,3) NOT NULL DEFAULT 1.000,
    transform_expr TEXT,
    deleted_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_lce_edge ON lineage_column_edge (src_fqn, tgt_fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_lce_src ON lineage_column_edge (src_fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_lce_tgt ON lineage_column_edge (tgt_fqn) WHERE deleted_at IS NULL;

-- 传递闭包（异步预计算，查询走此表；递归 CTE 仅用于重建兜底）
CREATE TABLE lineage_closure (
    ancestor_fqn   TEXT    NOT NULL,
    descendant_fqn TEXT    NOT NULL,
    depth          INTEGER NOT NULL,
    edge_count     INTEGER NOT NULL DEFAULT 1,
    rebuilt_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ancestor_fqn, descendant_fqn)
);
CREATE INDEX idx_lclos_anc ON lineage_closure (ancestor_fqn, depth);
CREATE INDEX idx_lclos_desc ON lineage_closure (descendant_fqn, depth);

-- =============================================================================
-- 10. 账号与授权（FR-6）
-- =============================================================================
CREATE TABLE account (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    account_name  TEXT        NOT NULL,
    account_type  TEXT,                    -- user / role
    host_pattern  TEXT,
    is_super      BOOLEAN     NOT NULL DEFAULT FALSE,
    is_locked     BOOLEAN     NOT NULL DEFAULT FALSE,
    last_login_at TIMESTAMPTZ,
    properties    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_account ON account (datasource_id, account_name, host_pattern) WHERE deleted_at IS NULL;

CREATE TABLE account_grant (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    datasource_id BIGINT      NOT NULL REFERENCES datasource (id),
    account_id    BIGINT      REFERENCES account (id),
    privilege     TEXT        NOT NULL,   -- SELECT / INSERT / UPDATE / DELETE / ALL
    object_type   TEXT        NOT NULL,   -- database / schema / table / column
    object_fqn    TEXT        NOT NULL,
    grantable     BOOLEAN     NOT NULL DEFAULT FALSE,
    detected_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX idx_grant_account ON account_grant (account_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_grant_object ON account_grant (object_fqn) WHERE deleted_at IS NULL;
CREATE INDEX idx_grant_ds ON account_grant (datasource_id, privilege) WHERE deleted_at IS NULL;

-- =============================================================================
-- 11. 采样（默认不落库，见 ADR-6；表结构预留，按月分区便于 TTL 整区 drop）
-- =============================================================================
CREATE TABLE sample_value (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    sampled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    column_id    BIGINT      NOT NULL,
    value_masked TEXT,                     -- 脱敏后样本（默认存此列）
    value_enc    BYTEA,                    -- 原文密文：仅在显式开启时写入
    value_hash   TEXT,                     -- 用于去重，不泄露内容
    sampled_by   TEXT,
    expires_at   TIMESTAMPTZ,
    PRIMARY KEY (id, sampled_at)
) PARTITION BY RANGE (sampled_at);
CREATE INDEX idx_sample_column ON sample_value (column_id, sampled_at DESC);
CREATE INDEX idx_sample_expire ON sample_value (expires_at);

-- =============================================================================
-- 12. 审计日志（按月分区）
-- =============================================================================
CREATE TABLE audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    tenant_id   BIGINT      NOT NULL DEFAULT 0,
    actor       TEXT,
    action      TEXT        NOT NULL,   -- sample / export / credential_change / manual_tag / ...
    entity_type TEXT,
    entity_fqn  TEXT,
    detail      JSONB       NOT NULL DEFAULT '{}'::jsonb,
    client_ip   INET,
    result      TEXT,
    PRIMARY KEY (id, occurred_at)
) PARTITION BY RANGE (occurred_at);
CREATE INDEX idx_audit_action ON audit_log (action, occurred_at DESC);
CREATE INDEX idx_audit_entity ON audit_log (entity_type, entity_fqn, occurred_at DESC);

-- =============================================================================
-- 13. 通知订阅与发送记录
-- =============================================================================
CREATE TABLE notification_subscription (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT      NOT NULL DEFAULT 0,
    subscriber    TEXT        NOT NULL,
    scope_type    TEXT        NOT NULL,   -- datasource / database / schema / table
    scope_fqn     TEXT,
    datasource_id BIGINT      REFERENCES datasource (id),  -- scope_type=datasource 时必填，其余为 NULL
    min_severity  TEXT        NOT NULL DEFAULT 'structural',
    channel       TEXT        NOT NULL,   -- webhook / email / slack
    channel_conf  JSONB       NOT NULL DEFAULT '{}'::jsonb,
    enabled       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notisub_scope ON notification_subscription (scope_type, scope_fqn) WHERE enabled;

CREATE TABLE notification_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    change_id    BIGINT,
    subscription_id BIGINT,
    channel      TEXT        NOT NULL,
    status       TEXT        NOT NULL,
    retry_count  INTEGER     NOT NULL DEFAULT 0,
    sent_at      TIMESTAMPTZ,
    error_message TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_notilog_change ON notification_log (change_id);

-- =============================================================================
-- 14. 初始数据：默认分级标准
-- =============================================================================
INSERT INTO classification_tag (tag_key, tag_name, category, grade_level, grade_code, description) VALUES
    ('L1_PUBLIC',   '公开',   'SECURITY', 1, 'L1', '可对外公开'),
    ('L2_INTERNAL', '内部',   'SECURITY', 2, 'L2', '仅限内部使用'),
    ('L3_SENSITIVE','敏感',   'SECURITY', 3, 'L3', '敏感数据，需授权访问'),
    ('L4_CORE',     '核心',   'SECURITY', 4, 'L4', '核心敏感数据，严格管控'),
    ('PII_PHONE',   '手机号', 'PII',      3, 'L3', '手机号码'),
    ('PII_IDCARD',  '身份证', 'PII',      4, 'L4', '身份证号码'),
    ('PII_EMAIL',   '邮箱',   'PII',      2, 'L2', '电子邮箱'),
    ('PII_NAME',    '姓名',   'PII',      3, 'L3', '自然人姓名'),
    ('PII_ADDRESS', '地址',   'PII',      3, 'L3', '住址/地址信息'),
    ('FIN_BANKCARD','银行卡', 'FINANCE',  4, 'L4', '银行卡号');

-- 识别规则示例
INSERT INTO classification_rule (tag_key, rule_kind, pattern, confidence, priority) VALUES
    ('PII_PHONE',   'column_name', 'phone',   0.600, 100),
    ('PII_PHONE',   'column_name', 'mobile',  0.600, 100),
    ('PII_PHONE',   'regex',       '^1[3-9]\\d{9}$', 0.900, 50),
    ('PII_IDCARD',  'column_name', 'id_card', 0.600, 100),
    ('PII_IDCARD',  'regex',       '^\\d{17}[\\dXx]$', 0.950, 50),
    ('PII_EMAIL',   'column_name', 'email',   0.700, 100),
    ('PII_EMAIL',   'regex',       '^[\\w.+-]+@[\\w-]+\\.[\\w.]+$', 0.900, 50),
    ('FIN_BANKCARD','column_name', 'bank_card', 0.600, 100),
    ('FIN_BANKCARD','regex',       '^\\d{16,19}$', 0.700, 80);

-- =============================================================================
-- 15. 补充表（模块详细设计 v1.1 引入）
-- =============================================================================

-- FR-13.6 实体历史名称（改名检测，MOD-02）
CREATE TABLE entity_alias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT        NOT NULL,   -- table / column
    entity_id   BIGINT      NOT NULL,   -- 稳定 ID（非 FQN）
    alias_fqn   TEXT        NOT NULL,   -- 曾用名
    valid_from  TIMESTAMPTZ NOT NULL DEFAULT now(),
    valid_to    TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_alias ON entity_alias (entity_type, alias_fqn);
CREATE INDEX idx_alias_entity ON entity_alias (entity_type, entity_id);

-- FR-5.7 画像历史（MOD-04，按月分区）
CREATE TABLE table_profile_history (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    profiled_date DATE        NOT NULL,
    table_id      BIGINT      NOT NULL,
    datasource_id BIGINT      NOT NULL,
    row_count     BIGINT,
    stats         JSONB       NOT NULL DEFAULT '{}'::jsonb,
    quality_score NUMERIC(5,2),
    profiled_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (id, profiled_date)
) PARTITION BY RANGE (profiled_date);
CREATE INDEX idx_prof_hist_table ON table_profile_history (table_id, profiled_date DESC);

-- FR-14 业务元数据（MOD-09）
CREATE TABLE business_term (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 0,
    term_code   TEXT   NOT NULL,
    term_name   TEXT   NOT NULL,
    domain      TEXT,
    definition  TEXT,
    owner       TEXT,
    status      TEXT   NOT NULL DEFAULT 'active',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_bterm_code ON business_term (term_code);

CREATE TABLE business_metadata (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id      BIGINT NOT NULL DEFAULT 0,
    entity_type    TEXT   NOT NULL,   -- table / column
    entity_id      BIGINT NOT NULL,
    alias          TEXT,
    business_desc  TEXT,
    domain         TEXT,
    owner_business TEXT,
    term_codes     JSONB  NOT NULL DEFAULT '[]'::jsonb,
    tags           JSONB  NOT NULL DEFAULT '{}'::jsonb,   -- business.* namespace tags (FR-14.4)
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_bmeta_entity ON business_metadata (entity_type, entity_id);
CREATE INDEX idx_bmeta_domain ON business_metadata (domain);
CREATE INDEX idx_bmeta_alias ON business_metadata USING gin (alias gin_trgm_ops);

-- FR-10 平台账号与权限（MOD-11）
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT NOT NULL DEFAULT 0,
    username        TEXT   NOT NULL,
    display_name    TEXT,
    email           TEXT,
    credential_hash TEXT,
    auth_source     TEXT   NOT NULL DEFAULT 'local',   -- local / ldap / oauth
    external_id     TEXT,
    status          TEXT   NOT NULL DEFAULT 'active',
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_appuser_name ON app_user (tenant_id, username);

CREATE TABLE role (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 0,
    role_code   TEXT   NOT NULL,
    role_name   TEXT   NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_role_code ON role (tenant_id, role_code);

CREATE TABLE permission (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_code   TEXT   NOT NULL,
    description TEXT
);
CREATE UNIQUE INDEX uq_perm_code ON permission (perm_code);

CREATE TABLE role_permission (
    role_id       BIGINT NOT NULL REFERENCES role (id),
    permission_id BIGINT NOT NULL REFERENCES permission (id),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL REFERENCES app_user (id),
    role_id BIGINT NOT NULL REFERENCES role (id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE data_policy (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT NOT NULL DEFAULT 0,
    subject_type TEXT  NOT NULL,   -- user / role
    subject_id  BIGINT NOT NULL,
    scope_type  TEXT   NOT NULL,   -- datasource / database / schema / table
    scope_fqn   TEXT   NOT NULL,   -- '*' 表示全部
    effect      TEXT   NOT NULL DEFAULT 'allow',   -- allow / deny
    actions     JSONB  NOT NULL DEFAULT '["read"]'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_dpolicy_subject ON data_policy (subject_type, subject_id);
CREATE INDEX idx_dpolicy_scope ON data_policy (scope_type, scope_fqn);

-- FR-6.7 业务库账号与平台用户关联
CREATE TABLE account_user_mapping (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL REFERENCES app_user (id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_acctuser ON account_user_mapping (account_id, user_id);

-- =============================================================================
-- 16. 协作与流程：审批流 + 工单（MOD-12，补全原范围排除项）
-- =============================================================================

-- 审批请求：资产上线 / 分类分级结果 / 敏感标注 / 删除 等需责任人审批的动作
CREATE TABLE approval_request (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT    NOT NULL DEFAULT 0,
    resource_type TEXT      NOT NULL,   -- asset / classification / sensitive_tag / datasource
    resource_fqn  TEXT      NOT NULL,
    action_type   TEXT      NOT NULL,   -- publish / classify / sensitive_tag / delete
    title         TEXT      NOT NULL,
    requested_by  TEXT      NOT NULL,
    approver      TEXT,                    -- 指定审批人（可空，由角色策略解析）
    status        TEXT      NOT NULL DEFAULT 'pending',  -- pending / approved / rejected
    priority      TEXT      NOT NULL DEFAULT 'P2',
    reason        TEXT,
    decided_at    TIMESTAMPTZ,
    decided_by    TEXT,
    decided_comment TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_approval_status ON approval_request (status, created_at DESC);
CREATE INDEX idx_approval_resource ON approval_request (resource_type, resource_fqn);
CREATE INDEX idx_approval_approver ON approval_request (approver);
ALTER TABLE approval_request
    ADD CONSTRAINT ck_approval_status CHECK (status IN ('pending','approved','rejected')),
    ADD CONSTRAINT ck_approval_action CHECK (action_type IN ('publish','classify','sensitive_tag','delete'));

-- 工单：数据问题 / 权限申请 / 破坏性变更自动跟进（MOD-06 联动）/ 其他
CREATE TABLE governance_ticket (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT    NOT NULL DEFAULT 0,
    title        TEXT      NOT NULL,
    description  TEXT,
    ticket_type  TEXT      NOT NULL DEFAULT 'data_issue',  -- data_issue / access_request / change_auto / other
    priority     TEXT      NOT NULL DEFAULT 'P2',
    status       TEXT      NOT NULL DEFAULT 'open',  -- open / in_progress / resolved / closed
    reporter     TEXT      NOT NULL,
    assignee     TEXT,
    related_fqn  TEXT,                    -- 关联资产 / 变更 FQN
    source       TEXT      NOT NULL DEFAULT 'manual',  -- manual / change_auto
    sla_due_at   TIMESTAMPTZ,
    resolved_at  TIMESTAMPTZ,
    closed_at    TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_ticket_status ON governance_ticket (status, created_at DESC);
CREATE INDEX idx_ticket_type ON governance_ticket (ticket_type);
CREATE INDEX idx_ticket_assignee ON governance_ticket (assignee);
CREATE INDEX idx_ticket_related ON governance_ticket (related_fqn);
ALTER TABLE governance_ticket
    ADD CONSTRAINT ck_ticket_status CHECK (status IN ('open','in_progress','resolved','closed')),
    ADD CONSTRAINT ck_ticket_type  CHECK (ticket_type IN ('data_issue','access_request','change_auto','other'));

-- 评论/处理记录（审批与工单共用）
CREATE TABLE governance_comment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT    NOT NULL DEFAULT 0,
    target_type TEXT      NOT NULL,   -- approval / ticket
    target_id   BIGINT    NOT NULL,
    author      TEXT      NOT NULL,
    body        TEXT      NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_gcomment_target ON governance_comment (target_type, target_id, created_at DESC);
ALTER TABLE governance_comment
    ADD CONSTRAINT ck_gcomment_target CHECK (target_type IN ('approval','ticket'));

COMMIT;

-- =============================================================================
-- 运维提示（不参与建表）
-- =============================================================================
-- 1. 分区表需每月预建下月分区，建议纳入 Alembic 或定时作业：
--    CREATE TABLE column_snapshot_YYYY_MM PARTITION OF column_snapshot
--        FOR VALUES FROM ('YYYY-MM-01') TO ('YYYY-MM+1-01');
--
-- 2. 保留窗口外清理用 DROP PARTITION（秒级），勿用 DELETE：
--    DROP TABLE column_snapshot_2026_01;
--
-- 3. 大表加索引须 CONCURRENTLY，且不能在事务块内执行：
--    CREATE INDEX CONCURRENTLY idx_xxx ON catalog_column (...);
--
-- 4. 级联删除请用软删除 + 异步分批，勿依赖 ON DELETE CASCADE（见设计文档 §5.3）。
