"""Profile persistence (D8) — ``05-1`` stage 2.

Why this module exists
----------------------
Profiling produces two different things that must not be conflated: the
*current* profile (one row per table, overwritten) and the *history* (one row
per table per day, never overwritten). ``table_profile`` has a unique index on
``table_id``; ``table_profile_history`` is RANGE-partitioned on
``profiled_date``. Writing both is a single unit of work here so a caller
cannot accidentally produce a history row without a current row.

Design note on history identity
------------------------------
``table_profile_history`` is partitioned by DATE, so its grain is
**one snapshot per table per day** — not one per run. Re-profiling twice in a
day therefore updates the day's row rather than appending a second one; a
second row would need a different ``profiled_date``, which is what the tests
use to assert AC-1.5. The ``id`` column is ``GENERATED BY DEFAULT AS
IDENTITY`` in the DDL, so supplying it explicitly is legal; we reuse the
current profile's id to keep the pair joinable without a second lookup.
"""
from __future__ import annotations

from datetime import date, datetime
from decimal import Decimal
from typing import Any

from sqlalchemy import delete, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from ..storage.models_governance import TableProfile, TableProfileHistory

__all__ = [
    "serialise_stats",
    "upsert_profile",
    "append_history",
    "get_profile",
    "list_history",
    "delete_profile",
]

STATUS_PENDING = "pending"
STATUS_RUNNING = "running"
STATUS_SUCCESS = "success"
STATUS_FAILED = "failed"
STATUS_SKIPPED = "skipped"


def serialise_stats(stats: dict[str, Any]) -> dict[str, Any]:
    """Make a stats payload JSONB-safe.

    Drivers hand back ``Decimal`` for NUMERIC aggregates and ``datetime``/
    ``date`` for temporal ones; JSONB rejects both. Numeric aggregates become
    floats (profiling does not need exact decimal semantics) and temporal ones
    become ISO strings so the UI can render them without re-parsing.
    """
    return _convert(stats)


def _convert(value: Any) -> Any:
    if isinstance(value, Decimal):
        return float(value)
    if isinstance(value, (datetime, date)):
        return value.isoformat()
    if isinstance(value, dict):
        return {key: _convert(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_convert(item) for item in value]
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    return str(value)


def upsert_profile(
    session: Session,
    *,
    table_id: int,
    datasource_id: int,
    row_count: int | None,
    column_count: int | None,
    stats: dict[str, Any],
    sample_rate: float | None,
    sampled_rows: int | None,
    profiled_at: datetime,
    duration_ms: int,
    status: str,
    error_message: str | None = None,
) -> TableProfile:
    """Insert or update the current profile for ``table_id``.

    Relies on the ``uq_profile_table`` unique index; ``updated_at`` is
    maintained by ``TimestampMixin``.
    """
    payload = {
        "datasource_id": datasource_id,
        "row_count": row_count,
        "column_count": column_count,
        "stats": serialise_stats(stats),
        "sample_rate": sample_rate,
        "sampled_rows": sampled_rows,
        "profiled_at": profiled_at,
        "duration_ms": duration_ms,
        "status": status,
        "error_message": error_message,
    }
    statement = pg_insert(TableProfile).values(table_id=table_id, **payload)
    statement = statement.on_conflict_do_update(
        index_elements=["table_id"], set_=payload
    )
    session.execute(statement)
    session.commit()
    return get_profile(session, table_id)  # type: ignore[return-value]


def append_history(
    session: Session,
    *,
    table_id: int,
    datasource_id: int,
    profiled_date: date,
    row_count: int | None,
    stats: dict[str, Any],
    quality_score: float | None = None,
) -> None:
    """Write (or refresh) the day's history row for ``table_id``."""
    current = get_profile(session, table_id)
    payload = {
        "row_count": row_count,
        "stats": serialise_stats(stats),
        "quality_score": quality_score,
        "profiled_at": datetime.now(),
    }
    statement = pg_insert(TableProfileHistory).values(
        id=current.id if current is not None else table_id,
        profiled_date=profiled_date,
        table_id=table_id,
        datasource_id=datasource_id,
        **payload,
    )
    statement = statement.on_conflict_do_update(
        index_elements=["id", "profiled_date"],
        set_=payload,
    )
    session.execute(statement)
    session.commit()


def get_profile(session: Session, table_id: int) -> TableProfile | None:
    """Current profile row, or ``None`` if the table has never been profiled."""
    return session.execute(
        select(TableProfile).where(TableProfile.table_id == table_id)
    ).scalar_one_or_none()


def list_history(
    session: Session, table_id: int, *, limit: int = 30
) -> list[TableProfileHistory]:
    """Most recent history rows for ``table_id``."""
    rows = session.execute(
        select(TableProfileHistory)
        .where(TableProfileHistory.table_id == table_id)
        .order_by(TableProfileHistory.profiled_date.desc())
        .limit(limit)
    ).scalars()
    return list(rows)


def delete_profile(session: Session, table_id: int) -> None:
    """Remove both current and historical rows (test helper)."""
    session.execute(
        delete(TableProfileHistory).where(TableProfileHistory.table_id == table_id)
    )
    session.execute(delete(TableProfile).where(TableProfile.table_id == table_id))
    session.commit()
